GET http://localhost:4000/user/me HTTP/1.1 
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjE5MGVmMTVmNjYzNDMyNDc4YjUyMGY4In0sImlhdCI6MTYzNjg5MDM3NSwiZXhwIjoxNjM2ODkzOTc1fQ.MKk6wERVAkUr_yBY1r62EI5GcXfoQyPNSCy6gtKD5aI