name: publish

# on: [push]

jobs:
  publish-tva-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the tva Docker image
      run: |
        docker build . --tag ghcr.io/talha-altair/tva:latest
        docker push ghcr.io/talha-altair/tva:latest